// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PairedDeviceManager.Api.Data;

namespace PairedDeviceManager.Api.Migrations
{
    [DbContext(typeof(PairedDeviceManagerContext))]
    partial class PairedDeviceManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PairedDeviceManager.Api.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<long?>("HubId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("PairedDeviceManager.Api.Models.Dwelling", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DwellingStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dwellings");
                });

            modelBuilder.Entity("PairedDeviceManager.Api.Models.Hub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DwellingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DwellingId");

                    b.ToTable("Hubs");
                });

            modelBuilder.Entity("PairedDeviceManager.Api.Models.Device", b =>
                {
                    b.HasOne("PairedDeviceManager.Api.Models.Hub", "Hub")
                        .WithMany("Devices")
                        .HasForeignKey("HubId");

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("PairedDeviceManager.Api.Models.Hub", b =>
                {
                    b.HasOne("PairedDeviceManager.Api.Models.Dwelling", null)
                        .WithMany("Hubs")
                        .HasForeignKey("DwellingId");
                });

            modelBuilder.Entity("PairedDeviceManager.Api.Models.Dwelling", b =>
                {
                    b.Navigation("Hubs");
                });

            modelBuilder.Entity("PairedDeviceManager.Api.Models.Hub", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
